// Shared list of unit / company names used by the Address Book filters.
export const UNIT_NAMES: string[] = [
  "Sylhet EZ",
  "Corporate Office",
  "Jinnat Apparels Ltd",
  "Jinnat Knitwears Ltd",
  "Jinnat Fashions Ltd",
  "Matin Spinning Mills PLC",
  "Thanbee Print World Ltd",
  "Hamza Textiles Ltd",
  "Flamingo Fashions Ltd",
  "DB Tex Ltd",
  "Dulal Brothers Ltd",
  "Color City Ltd",
  "DBL Digital Ltd",
  "Parkway Packaging and Printing Ltd",
  "Mymun Textiles Ltd",
  "DBL Pharmaceuticals Ltd",
  "DBL Ceramics Ltd",
  "DBL Telecom Ltd",
  "DBL Distributions Ltd",
  "DBL Lifestyles Ltd",
  "Digital Corporate",
  "ECO Thread Plant",
  "DBL Dredging Ltd.",
  "Farmgate Office",
  "Mawna Fashions Ltd.",
  "Ceramics Plant",
  "DB TRIMS Ltd.",
  "Jinnat Complex",
  "Mymun Complex",
  "Glory Textile and Apparels Limited",
  "DBL Industrial Park Ltd",
  "Knitting",
  "Thanbee Complex",
  "DBL Textile Recycling Ltd",
  "Matin Complex",
  "Jinnat Textile Mills Ltd",
  "Textile Testing Services Ltd",
  "Atelier Sourcing Ltd",
  "Mawna Fashions Ltd",
  "DBL Tours and Travels Limited",
  "Chittagong C and F Office",
  "Ceramics Field",
  "Flamingo2",
  "Dredging Office",
  "JKL2",
  "Pharma Field",
  "Pharma Plant",
  "Lifestyle Corporate",
  "Pharma Corporate",
  "ECO Thread Corporate",
  "DBTrims Plant",
  "Ceramics Corporate",
  "PPPL Corporate",
  "EUDB Accessories Limited",
  "PPPL Plant",
  "DBL Healthcare Ltd",
  "EUDB",
  "DBLCL",
  "Jinnat Knitting Ltd",
  "DBL Pharma",
  "FFL2",
  "eco Plant",
  "MSML Complex",
  "DTRL (Matin Complex)",
];

export const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
