import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import moment from "moment";
import { Button } from "antd";
import { FilePdfOutlined } from "@ant-design/icons";
import { useGetMeQuery } from "../../app/api/userApi";
import logo from "../../assets/logo.png";

interface Props {
  PDFFileName: string;
  fileHeader: string;
  PDFHeader: string[]; // Field names
  PDFData: any; // Single entry object
}

const PDFDownload: React.FC<Props> = ({
  PDFFileName,
  fileHeader,
  PDFHeader,
  PDFData,
}) => {
  const date_time = moment().format("DD-MM-YYYY");
  const time_stamp = moment().format("hh:mm A");
  const { data } = useGetMeQuery();
  const { name, employee_id, designation, unit_name, department } = data?.data || {};

  const savePDF = async () => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // =====================
    // HEADER SECTION
    // =====================
    
    // Add Logo (centered at top)
    const img = new Image();
    img.src = logo;
    await new Promise((resolve) => {
      img.onload = () => {
        const logoWidth = 35;
        const logoHeight = 35;
        const logoX = (pageWidth - logoWidth) / 2;
        doc.addImage(img, "PNG", logoX, 10, logoWidth, logoHeight);
        resolve(true);
      };
    });

    // Title below logo with proper spacing
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(26, 35, 126);
    doc.text(fileHeader, pageWidth / 2, 52, { align: "center" });

    // Subtitle line
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.8);
    doc.line(14, 58, pageWidth - 14, 58);

    // Generated timestamp (top right corner)
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`Generated: ${date_time}`, pageWidth - 14, 12, {
      align: "right",
    });
    doc.text(`Time: ${time_stamp}`, pageWidth - 14, 17, {
      align: "right",
    });

    // =====================
    // REPORT INFO SECTION
    // =====================
    
    let currentY = 68;

    // Info Box with gradient-like effect (double border)
    doc.setFillColor(240, 242, 245);
    doc.roundedRect(14, currentY, pageWidth - 28, 42, 3, 3, "F");

    // Outer border (darker)
    doc.setDrawColor(200, 210, 220);
    doc.setLineWidth(0.5);
    doc.roundedRect(14, currentY, pageWidth - 28, 42, 3, 3, "S");

    // Inner border accent (navy)
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.3);
    doc.roundedRect(14.5, currentY + 0.5, pageWidth - 29, 41, 3, 3, "S");

    // Section Title with icon-like decoration
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(26, 35, 126);
    
    // Add a small circle/dot as icon
    doc.setFillColor(26, 35, 126);
    doc.circle(18, currentY + 4.5, 1.2, "F");
    
    doc.text("REPORT GENERATED BY", 21, currentY + 6);
    
    // Underline for section title
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.5);
    doc.line(21, currentY + 7.5, 65, currentY + 7.5);

    currentY += 14;

    // Info Details with improved styling
    doc.setFontSize(9);
    doc.setTextColor(40);

    const leftCol = 20;
    const rightCol = pageWidth / 2 + 8;
    const lineHeight = 7;
    const labelWidth = 28;

    // Helper function to add a row with label and value
    const addInfoRow = (label: string, value: string, x: number, y: number) => {
      // Label with background
      doc.setFillColor(230, 235, 240);
      doc.roundedRect(x, y - 4, labelWidth, 5.5, 1, 1, "F");
      
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 35, 126);
      doc.text(label, x + 1.5, y);
      
      // Value
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
      
      // Truncate long text if needed
      const maxWidth = (pageWidth / 2) - labelWidth - 12;
      const truncatedValue = doc.splitTextToSize(value, maxWidth)[0];
      doc.text(truncatedValue, x + labelWidth + 2, y);
    };

    // Left Column
    addInfoRow("Name:", name || "N/A", leftCol, currentY);
    currentY += lineHeight;
    addInfoRow("Employee ID:", employee_id || "N/A", leftCol, currentY);

    // Right Column (reset Y for right side)
    let rightY = currentY - lineHeight;
    addInfoRow("Designation:", designation || "N/A", rightCol, rightY);
    rightY += lineHeight;
    addInfoRow("Unit:", unit_name || "N/A", rightCol, rightY);

    currentY += lineHeight;
    if (department) {
      addInfoRow("Department:", department, leftCol, currentY);
      currentY += lineHeight;
    }

    // Add a subtle bottom accent line
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.3);
    const boxBottom = 68 + 42;
    doc.line(18, boxBottom - 2, pageWidth - 18, boxBottom - 2);

    // =====================
    // REPORT DATA SECTION
    // =====================
    
    const tableStartY = 68 + 42 + 8; // Info box Y + height + gap

    // Section Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(26, 35, 126);
    
    // Add icon decoration
    doc.setFillColor(26, 35, 126);
    doc.circle(14, tableStartY - 1.5, 1.2, "F");
    
    doc.text("REPORT DETAILS", 17, tableStartY);
    
    // Underline
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.5);
    doc.line(17, tableStartY + 1.5, 60, tableStartY + 1.5);

    // Prepare table data - Match PDFHeader order with PDFData
    const tableBody = PDFHeader.map((field) => {
      const value = PDFData[field];
      return [
        {
          content: field,
          styles: { 
            fontStyle: "bold" as const, 
            textColor: [40, 40, 40] as [number, number, number],
            fontSize: 9,
          },
        },
        {
          content: value !== undefined && value !== null ? String(value) : "-",
          styles: { 
            textColor: [60, 60, 60] as [number, number, number],
            fontSize: 9,
          },
        },
      ];
    });

    // Draw table with enhanced styling
    autoTable(doc, {
      startY: tableStartY + 5,
      head: [
        [
          {
            content: "Field",
            styles: { halign: "center" as const, fontStyle: "bold" as const },
          },
          {
            content: "Value",
            styles: { halign: "center" as const, fontStyle: "bold" as const },
          },
        ],
      ],
      body: tableBody,
      theme: "striped",
      headStyles: {
        fillColor: [26, 35, 126], // Deep navy blue
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: "bold",
        halign: "center",
        cellPadding: { top: 4, right: 5, bottom: 4, left: 5 },
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: { top: 4, right: 5, bottom: 4, left: 5 },
      },
      alternateRowStyles: {
        fillColor: [248, 249, 250], // Very light gray for alternate rows
      },
      columnStyles: {
        0: { 
          cellWidth: 65, 
          halign: "left",
          fontStyle: "bold",
        },
        1: { 
          cellWidth: 115, 
          halign: "left",
        },
      },
      styles: {
        lineColor: [220, 220, 220],
        lineWidth: 0.3,
        font: "helvetica",
        overflow: "linebreak",
        cellPadding: 4,
      },
      margin: { left: 14, right: 14 },
    });

    // =====================
    // FOOTER SECTION
    // =====================
    
    const finalY = (doc as any).lastAutoTable.finalY || tableStartY + 50;
    
    // Add decorative line above footer
    doc.setDrawColor(26, 35, 126);
    doc.setLineWidth(0.5);
    doc.line(14, pageHeight - 20, pageWidth - 14, pageHeight - 20);

    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.setFont("helvetica", "italic");
    doc.text(
      `This is a system-generated report. No signature required.`,
      pageWidth / 2,
      pageHeight - 15,
      { align: "center" }
    );

    // Page number
    doc.setFont("helvetica", "normal");
    doc.text(`Page 1 of 1`, pageWidth / 2, pageHeight - 10, {
      align: "center",
    });

    // Confidentiality notice (optional)
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(
      `Report Date: ${date_time}`,
      14,
      pageHeight - 10
    );
    doc.text(
      `Document ID: ${PDFFileName}`,
      pageWidth - 14,
      pageHeight - 10,
      { align: "right" }
    );

    // Save with timestamp
    doc.save(`${date_time}_${PDFFileName}.pdf`);
  };

  return (
    <Button
      onClick={savePDF}
      type="primary"
      icon={<FilePdfOutlined />}
      style={{
        backgroundColor: "#d32f2f",
        borderColor: "#d32f2f",
        color: "#fff",
        fontWeight: 500,
        height: 32,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        boxShadow: "0 2px 4px rgba(211, 47, 47, 0.2)",
      }}
      size="middle"
    >
      PDF
    </Button>
  );
};

export default PDFDownload;